version: "2"

services:
  db-mysql:
    image: mysql
    environment :
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./data/mysql:/var/lib/mysql

  app-wordpress:
    image: wordpress
    environment:
      - WORDPRESS_DB_HOST=db-mysql:3306
      - WORDPRESS_DB_PASSWORD=password
    ports:
      - 10180:80

  app-dolibarr:
    build: ./amap-dolibarr
    ports:
      - 10280:80

  app-garradin:
    build: ./amap-garradin
    ports:
      - 10380:80

  app-galette:
    build: ./amap-galette
    ports:
      - 10480:80